review raster_cutter
geometalab/qgis-raster-cutter pull request #2
Opened 2022-06-15 07:25 UTC by hixi

2022-06-15 08:07 UTC, hixi reviewed
@underwhelmingToaster

2022-06-15 08:07 UTC, hixi commented on raster_cutter.py
> +        raise Exception('Could not find . in path')
This error is technically correct, but can we be more specific, which the underlying problem is (even from the code I don't know, what the issue is). Does this test for path exists and path isdir?

2022-06-15 08:07 UTC, hixi commented on raster_cutter.py
>  def pre_launch_checks():
This function doesn't seem to be used anywhere, if not required by magic (pyqt), remov it.

2022-06-20 07:51 UTC, underwhelmingToaster requested changes

2022-06-20 07:51 UTC, underwhelmingToaster commented on raster_cutter.py
> +            + '# projection: EPSG:2056 - CH1903+ / LV95'
@hixi Was this auto-format? I think the previous version makes more sense because each line is a line in the generated doc.

2022-06-20 10:38 UTC, underwhelmingToaster commented
Thanks @hixi for the review. Implemented suggestions.

2022-06-20 10:38 UTC, closed without merging